### ISSUE TITLE
What is the 'Get D01 (float)' node?

### ISSUE THREAD

**Issue by michelepanegrossi** [keijiro/SdfVfxSamples#8]
Hello,

I am trying to understand what the 'Get D01 (float)' node is, in the stickies VFX graph. I cannot find that node in the list of available nodes and in the docs. How is it generated and what is it?

Many thanks!

**Comment by keijiro** [comment]
That's a custom attribute.

https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@14.0/manual/Operator-GetCustomAttribute.html
